#! /bin/sh
### BEGIN INIT INFO
# Provides:          thread-apt-server
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Thread APT server
# Description:       Thread APT server
### END INIT INFO

set -u

NAME=thread-apt-server
DAEMON=/usr/sbin/thread-apt-server

RUNPATH=/var/run/${NAME}
PIDFILE=${RUNPATH}/${NAME}.pid
LOGFILE=/var/log/${NAME}/${NAME}.log

BASE_DIR=/srv/apt.srv.thread.com
GPG_HOME=/srv/apt.srv.thread.com/gpg
GPG_DEFAULT_KEY=5F3700E8

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

test -x ${DAEMON} || exit 0

. /lib/lsb/init-functions

case "${1:-}" in
	start)
		log_daemon_msg "Starting ${NAME}" ${NAME}

		for FILE in ${PIDFILE} ${LOGFILE}
		do
			mkdir -p $(dirname ${FILE})
			chown www-data:www-data $(dirname ${FILE})
		done

                start-stop-daemon --start --oknodo --chuid www-data:www-data \
                    --pidfile ${PIDFILE} \
		    --chdir / \
                    --exec ${DAEMON} -- \
                    --pidfile ${PIDFILE} \
		    --verbosity=1 \
		    --base-dir ${BASE_DIR} \
		    --gpg-home ${GPG_HOME} \
		    --gpg-default-key ${GPG_DEFAULT_KEY} \
		    --logfile ${LOGFILE}

		log_end_msg $?
        ;;

	stop)
		log_daemon_msg "Stopping ${NAME}" ${NAME}

		if start-stop-daemon --stop --quiet --retry 10 --oknodo \
			--pidfile ${PIDFILE}
		then
			rm -rf ${RUNPATH}
			log_end_msg $?
		else
			rm -rf ${RUNPATH}
			log_end_msg $?
			exit 1
		fi
	;;

	restart|force-reload)
		${0} stop
		${0} start
        ;;

	*)
		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
		exit 1
        ;;
esac
