#! /bin/sh
### BEGIN INIT INFO
# Provides:          thread-apt-server
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Thread APT server
# Description:       Thread APT server
### END INIT INFO

set -u

NAME=thread-apt-server
DAEMON=/usr/sbin/thread-apt-server

RUNPATH=/var/run/${NAME}
PIDFILE=${RUNPATH}/${NAME}.pid
LOGFILE=/var/log/${NAME}/${NAME}.log

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

test -x ${DAEMON} || exit 0

. /lib/lsb/init-functions

# Defaults
ARCHIVE_ROOT="/var/lib/thread-apt-server/archive"
GPG_HOME="/var/lib/thread-apt-server/gpghome"
ARCHIVE="stable"
ORIGIN="thread-apt-server"
PORT="3333"
BIND="127.0.0.1"
USER="www-data"
GROUP="www-data"

if [ -r /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

case "${1:-}" in
	start)
		log_daemon_msg "Starting ${NAME}" ${NAME}

		for FILE in ${PIDFILE} ${LOGFILE}
		do
			mkdir -p $(dirname ${FILE})
			chown ${USER}:${GROUP} $(dirname ${FILE})
		done

                start-stop-daemon --start --oknodo --chuid ${USER}:${GROUP} \
			--pidfile ${PIDFILE} \
			--chdir / \
			--exec ${DAEMON} -- \
			--pidfile ${PIDFILE} \
			--logfile ${LOGFILE} \
			--verbosity=1 \
			--archive-root ${ARCHIVE_ROOT} \
			--gpg-home ${GPG_HOME} \
			--archive ${ARCHIVE} \
			--origin ${ORIGIN} \
			--port ${PORT} \
			--bind ${BIND} \
			--
		log_end_msg $?
        ;;

	stop)
		log_daemon_msg "Stopping ${NAME}" ${NAME}

		if start-stop-daemon --stop --quiet --retry 10 --oknodo \
			--pidfile ${PIDFILE}
		then
			rm -rf ${RUNPATH}
			log_end_msg $?
		else
			rm -rf ${RUNPATH}
			log_end_msg $?
			exit 1
		fi
	;;

	restart|force-reload)
		${0} stop
		${0} start
        ;;

	*)
		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
		exit 1
        ;;
esac
