#!/bin/sh

set -eu

ARCHIVE_ROOT="/var/lib/thread-apt-server/archive"
GPG_HOME="/var/lib/thread-apt-server/gpghome"
USER="www-data"
GROUP="www-data"

case "${1}" in
	configure)
		if [ ! -d "${ARCHIVE_ROOT}" ]
		then
			mkdir -p "${ARCHIVE_ROOT}"
			chown -R ${USER}:${GROUP} "${ARCHIVE_ROOT}"
		fi

		if [ ! -d "${GPG_HOME}" ]
		then
			mkdir -p "${GPG_HOME}"
			chown -R ${USER}:${GROUP} "${GPG_HOME}"
			chmod 700 "${GPG_HOME}"

			echo "I: Generating GnuPG key in ${GPG_HOME}..."
			su ${USER} -c "gpg --batch --homedir ${GPG_HOME} --gen-key -" <<EOF
Key-Type: RSA
Key-Length: 2048
Subkey-Type: ELG-E
Subkey-Length: 1024
Name-Real: thread-apt-server
Expire-Date: 0
%commit
EOF
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
