#!/bin/sh

#DEBHELPER#

set -e

ARCHIVE_ROOT="/var/lib/aptly"
GPG_HOME="/var/lib/aptly/gpghome"

if [ "$1" = "purge" ]
then
	rm -rf /var/run/aptly
	rm -rf /var/log/aptly

	rm -rf "${ARCHIVE_ROOT}"
	rm -rf "${GPG_HOME}"
fi
